/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as KeranjangRouteImport } from './routes/keranjang'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdukIndexRouteImport } from './routes/produk.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProdukSlugRouteImport } from './routes/produk.$slug'
import { Route as AdminProdukRouteImport } from './routes/admin.produk'
import { Route as AdminPesananRouteImport } from './routes/admin.pesanan'
import { Route as AdminPengaturanRouteImport } from './routes/admin.pengaturan'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminLaporanRouteImport } from './routes/admin.laporan'
import { Route as AdminKategoriRouteImport } from './routes/admin.kategori'
import { Route as AdminInventoriRouteImport } from './routes/admin.inventori'

const KeranjangRoute = KeranjangRouteImport.update({
  id: '/keranjang',
  path: '/keranjang',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdukIndexRoute = ProdukIndexRouteImport.update({
  id: '/produk/',
  path: '/produk/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdukSlugRoute = ProdukSlugRouteImport.update({
  id: '/produk/$slug',
  path: '/produk/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProdukRoute = AdminProdukRouteImport.update({
  id: '/admin/produk',
  path: '/admin/produk',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPesananRoute = AdminPesananRouteImport.update({
  id: '/admin/pesanan',
  path: '/admin/pesanan',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPengaturanRoute = AdminPengaturanRouteImport.update({
  id: '/admin/pengaturan',
  path: '/admin/pengaturan',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLaporanRoute = AdminLaporanRouteImport.update({
  id: '/admin/laporan',
  path: '/admin/laporan',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminKategoriRoute = AdminKategoriRouteImport.update({
  id: '/admin/kategori',
  path: '/admin/kategori',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInventoriRoute = AdminInventoriRouteImport.update({
  id: '/admin/inventori',
  path: '/admin/inventori',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/keranjang': typeof KeranjangRoute
  '/admin/inventori': typeof AdminInventoriRoute
  '/admin/kategori': typeof AdminKategoriRoute
  '/admin/laporan': typeof AdminLaporanRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pengaturan': typeof AdminPengaturanRoute
  '/admin/pesanan': typeof AdminPesananRoute
  '/admin/produk': typeof AdminProdukRoute
  '/produk/$slug': typeof ProdukSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/produk/': typeof ProdukIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/keranjang': typeof KeranjangRoute
  '/admin/inventori': typeof AdminInventoriRoute
  '/admin/kategori': typeof AdminKategoriRoute
  '/admin/laporan': typeof AdminLaporanRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pengaturan': typeof AdminPengaturanRoute
  '/admin/pesanan': typeof AdminPesananRoute
  '/admin/produk': typeof AdminProdukRoute
  '/produk/$slug': typeof ProdukSlugRoute
  '/admin': typeof AdminIndexRoute
  '/produk': typeof ProdukIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/keranjang': typeof KeranjangRoute
  '/admin/inventori': typeof AdminInventoriRoute
  '/admin/kategori': typeof AdminKategoriRoute
  '/admin/laporan': typeof AdminLaporanRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pengaturan': typeof AdminPengaturanRoute
  '/admin/pesanan': typeof AdminPesananRoute
  '/admin/produk': typeof AdminProdukRoute
  '/produk/$slug': typeof ProdukSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/produk/': typeof ProdukIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/keranjang'
    | '/admin/inventori'
    | '/admin/kategori'
    | '/admin/laporan'
    | '/admin/login'
    | '/admin/pengaturan'
    | '/admin/pesanan'
    | '/admin/produk'
    | '/produk/$slug'
    | '/admin/'
    | '/produk/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/keranjang'
    | '/admin/inventori'
    | '/admin/kategori'
    | '/admin/laporan'
    | '/admin/login'
    | '/admin/pengaturan'
    | '/admin/pesanan'
    | '/admin/produk'
    | '/produk/$slug'
    | '/admin'
    | '/produk'
  id:
    | '__root__'
    | '/'
    | '/checkout'
    | '/keranjang'
    | '/admin/inventori'
    | '/admin/kategori'
    | '/admin/laporan'
    | '/admin/login'
    | '/admin/pengaturan'
    | '/admin/pesanan'
    | '/admin/produk'
    | '/produk/$slug'
    | '/admin/'
    | '/produk/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  KeranjangRoute: typeof KeranjangRoute
  AdminInventoriRoute: typeof AdminInventoriRoute
  AdminKategoriRoute: typeof AdminKategoriRoute
  AdminLaporanRoute: typeof AdminLaporanRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPengaturanRoute: typeof AdminPengaturanRoute
  AdminPesananRoute: typeof AdminPesananRoute
  AdminProdukRoute: typeof AdminProdukRoute
  ProdukSlugRoute: typeof ProdukSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ProdukIndexRoute: typeof ProdukIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/keranjang': {
      id: '/keranjang'
      path: '/keranjang'
      fullPath: '/keranjang'
      preLoaderRoute: typeof KeranjangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produk/': {
      id: '/produk/'
      path: '/produk'
      fullPath: '/produk/'
      preLoaderRoute: typeof ProdukIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produk/$slug': {
      id: '/produk/$slug'
      path: '/produk/$slug'
      fullPath: '/produk/$slug'
      preLoaderRoute: typeof ProdukSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/produk': {
      id: '/admin/produk'
      path: '/admin/produk'
      fullPath: '/admin/produk'
      preLoaderRoute: typeof AdminProdukRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pesanan': {
      id: '/admin/pesanan'
      path: '/admin/pesanan'
      fullPath: '/admin/pesanan'
      preLoaderRoute: typeof AdminPesananRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pengaturan': {
      id: '/admin/pengaturan'
      path: '/admin/pengaturan'
      fullPath: '/admin/pengaturan'
      preLoaderRoute: typeof AdminPengaturanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/laporan': {
      id: '/admin/laporan'
      path: '/admin/laporan'
      fullPath: '/admin/laporan'
      preLoaderRoute: typeof AdminLaporanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/kategori': {
      id: '/admin/kategori'
      path: '/admin/kategori'
      fullPath: '/admin/kategori'
      preLoaderRoute: typeof AdminKategoriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/inventori': {
      id: '/admin/inventori'
      path: '/admin/inventori'
      fullPath: '/admin/inventori'
      preLoaderRoute: typeof AdminInventoriRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  KeranjangRoute: KeranjangRoute,
  AdminInventoriRoute: AdminInventoriRoute,
  AdminKategoriRoute: AdminKategoriRoute,
  AdminLaporanRoute: AdminLaporanRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPengaturanRoute: AdminPengaturanRoute,
  AdminPesananRoute: AdminPesananRoute,
  AdminProdukRoute: AdminProdukRoute,
  ProdukSlugRoute: ProdukSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  ProdukIndexRoute: ProdukIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
